stages:
  - build

build:
  stage: build
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build
  cache:
    paths:
      - ./node_modules
    artifacts:
      expire_in: 1 hour
      paths:
        - dist/my-app
      only:
        - master

tests:
  stage: tests
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng test --watch=false
  cache:
    paths:
      - ./node_modules
  only:
    - master